/**
 * Image library — reads /images/manifest.json (generated by
 * `bun run images:manifest`) and exposes typed helpers for the UI.
 *
 * Folder structure:
 *   public/images/<category>/photo.jpg                → loose photo
 *   public/images/<category>/<album-slug>/photo.jpg   → album photo
 *
 * Drop new files / album folders, re-run the script — no code changes needed.
 * Designed to handle 8,000+ images with client-side pagination.
 */

export type CategoryKey =
  | "wedding"
  | "pre-wedding"
  | "baby"
<<<<<<< HEAD
  | "Maternity"
=======
>>>>>>> b5905f9 (Fresh clean commit)
  | "events"
  | "commercial"
  | "team";

export type Album = {
  photos: string[];
  events?: Record<string, string[]>;
<<<<<<< HEAD
<<<<<<< HEAD
  videos?: string[];
=======
>>>>>>> b5905f9 (Fresh clean commit)
=======
  videos?: string[];
>>>>>>> 70848b6 (Update contact details, instagram, portfolio filters, add shweta-pranav pre-wedding photos, remove large video files from tracking)
};

export type CategoryData = {
  albums: Record<string, Album>;
  loose: string[];
<<<<<<< HEAD
<<<<<<< HEAD
  videos?: string[];
=======
>>>>>>> b5905f9 (Fresh clean commit)
=======
  videos?: string[];
>>>>>>> 70848b6 (Update contact details, instagram, portfolio filters, add shweta-pranav pre-wedding photos, remove large video files from tracking)
};

export type Manifest = {
  generatedAt: string;
  total: number;
  categories: Partial<Record<CategoryKey, CategoryData>>;
};

export const CATEGORY_LABELS: Record<CategoryKey, string> = {
  wedding: "Wedding",
  "pre-wedding": "Pre-Wedding",
  baby: "Baby",
<<<<<<< HEAD
  Maternity: "Maternity",
=======
>>>>>>> b5905f9 (Fresh clean commit)
  events: "Events",
  commercial: "Commercial",
  team: "Team",
};

export const HIGHLIGHTS_PER_CATEGORY = 8;
export const IMAGES_PER_PAGE = 16;

export const PUBLIC_CATEGORIES: CategoryKey[] = [
  "wedding",
  "pre-wedding",
  "baby",
<<<<<<< HEAD
  "Maternity",
<<<<<<< HEAD
=======
  "events",
  "commercial",
>>>>>>> b5905f9 (Fresh clean commit)
=======
>>>>>>> 70848b6 (Update contact details, instagram, portfolio filters, add shweta-pranav pre-wedding photos, remove large video files from tracking)
];

/* ─── Manifest loading (cached + deduped) ─── */

let cache: Manifest | null = null;
let inflight: Promise<Manifest> | null = null;

const EMPTY: Manifest = { generatedAt: "", total: 0, categories: {} };

/** Detect old manifest format (string[]) and convert to new CategoryData */
function normalizeManifest(raw: any): Manifest {
  if (!raw || typeof raw !== "object") return EMPTY;
  const cats: Manifest["categories"] = {};
  const rawCats = raw.categories ?? {};
  for (const [key, val] of Object.entries(rawCats)) {
    if (Array.isArray(val)) {
      // OLD format: categories[key] = string[]  → migrate to { albums: {}, loose: [...] }
      cats[key as CategoryKey] = { albums: {}, loose: val as string[] };
    } else if (val && typeof val === "object") {
      // NEW format: already { albums, loose }
      const v = val as any;
      const albumsRecord: Record<string, Album> = {};
      for (const [aKey, aVal] of Object.entries(v.albums ?? {})) {
        const albumVal = aVal as any;
<<<<<<< HEAD
albumsRecord[aKey] = {
            photos: albumVal.photos ?? [],
            events: albumVal.events ?? {},
            videos: albumVal.videos ?? (albumVal.video ? [albumVal.video] : []),
          };
<<<<<<< HEAD
=======
        albumsRecord[aKey] = {
          photos: albumVal.photos ?? [],
          events: albumVal.events ?? {},
        };
>>>>>>> b5905f9 (Fresh clean commit)
=======
>>>>>>> 70848b6 (Update contact details, instagram, portfolio filters, add shweta-pranav pre-wedding photos, remove large video files from tracking)
      }
      cats[key as CategoryKey] = {
        albums: albumsRecord,
        loose: v.loose ?? [],
      };
    }
  }
  return {
    generatedAt: raw.generatedAt ?? "",
    total: raw.total ?? 0,
    categories: cats,
  };
}

export async function loadManifest(): Promise<Manifest> {
  if (cache) return cache;
  if (inflight) return inflight;
  inflight = fetch("/images/manifest.json")
    .then((r) => (r.ok ? r.json() : EMPTY))
    .catch(() => EMPTY)
    .then((raw) => {
      const m = normalizeManifest(raw);
      cache = m;
      inflight = null;
      return m;
    });
  return inflight;
}

/* ─── Gallery item type ─── */

export type GalleryItem = {
  src: string;
  category: CategoryKey;
  label: string;
};

/* ─── Album info type (for portfolio page cards) ─── */

export type AlbumInfo = {
  slug: string;
  category: CategoryKey;
  displayName: string;
  cover: string;       // first photo
  coverAlt: string;    // second photo (for collage) or same as cover
  photoCount: number;
<<<<<<< HEAD
<<<<<<< HEAD
  videos?: string[];   // optional videos for album
=======
>>>>>>> b5905f9 (Fresh clean commit)
=======
  videos?: string[];   // optional videos for album
>>>>>>> 70848b6 (Update contact details, instagram, portfolio filters, add shweta-pranav pre-wedding photos, remove large video files from tracking)
};

/* ─── Helper: get all photos for a category (albums + loose) ─── */

<<<<<<< HEAD
<<<<<<< HEAD
function getAllPhotos(catData: CategoryData, category?: CategoryKey): string[] {
=======
function getAllPhotos(catData: CategoryData): string[] {
>>>>>>> b5905f9 (Fresh clean commit)
=======
function getAllPhotos(catData: CategoryData, category?: CategoryKey): string[] {
>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
  const all: string[] = [];
  if (catData.albums) {
    for (const album of Object.values(catData.albums)) {
      if (album?.photos) all.push(...album.photos);
      if (album?.events) {
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
        // For wedding category, prioritize "wedding" event photos
        if (category === "wedding") {
          const eventEntries = Object.entries(album.events);
          for (const [key, evPhotos] of [...eventEntries.filter(([k]) => k.toLowerCase() === "wedding"),
              ...eventEntries.filter(([k]) => k.toLowerCase() !== "wedding")]) {
            all.push(...evPhotos);
          }
        } else {
          for (const evPhotos of Object.values(album.events)) {
            all.push(...evPhotos);
          }
<<<<<<< HEAD
=======
        for (const evPhotos of Object.values(album.events)) {
          all.push(...evPhotos);
>>>>>>> b5905f9 (Fresh clean commit)
=======
>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
        }
      }
    }
  }
  if (catData.loose) all.push(...catData.loose);
  return all;
}

/* ─── Helper: slug → display name ─── */

export function albumDisplayName(slug: string, category: CategoryKey): string {
  // For wedding/pre-wedding, format "name1-name2" as "Name1 & Name2"
  if (category === "wedding" || category === "pre-wedding") {
    const parts = slug.split("-");
    if (parts.length === 2) {
      return parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join(" & ");
    }
  }
  // General: "my-album-name" → "My Album Name"
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/* ─── Get all albums across public categories ─── */

export function getAlbums(manifest: Manifest, filterCat?: CategoryKey): AlbumInfo[] {
  const albums: AlbumInfo[] = [];

  for (const cat of PUBLIC_CATEGORIES) {
    if (filterCat && filterCat !== cat) continue;
    const data = manifest.categories[cat];
    if (!data) continue;

<<<<<<< HEAD
<<<<<<< HEAD
// Named albums
=======
    // Named albums
>>>>>>> b5905f9 (Fresh clean commit)
=======
// Named albums
>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
    if (data.albums) {
      for (const [slug, album] of Object.entries(data.albums)) {
        let totalCount = album?.photos?.length || 0;
        let cover1 = album?.photos?.[0];
        let cover2 = album?.photos?.[1];

        if (album?.events) {
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
          // Prioritize "wedding" event for cover selection in wedding category
          const eventEntries = Object.entries(album.events);
          const prioritizedEvents = cat === "wedding"
            ? [...eventEntries.filter(([k]) => k.toLowerCase() === "wedding"),
                ...eventEntries.filter(([k]) => k.toLowerCase() !== "wedding")]
            : eventEntries;

          for (const evPhotos of prioritizedEvents.map(([_, v]) => v)) {
<<<<<<< HEAD
=======
          for (const evPhotos of Object.values(album.events)) {
>>>>>>> b5905f9 (Fresh clean commit)
=======
>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
            totalCount += evPhotos.length;
            if (!cover1) { cover1 = evPhotos[0]; cover2 = evPhotos[1]; }
            else if (!cover2) { cover2 = evPhotos[0]; }
          }
        }
<<<<<<< HEAD
<<<<<<< HEAD

        if (!totalCount) continue;

=======
        
        if (!totalCount) continue;
        
<<<<<<< HEAD
>>>>>>> b5905f9 (Fresh clean commit)
=======

        if (!totalCount) continue;

>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
        albums.push({
          slug,
          category: cat,
          displayName: albumDisplayName(slug, cat),
          cover: cover1 || "/placeholder.svg",
          coverAlt: cover2 ?? cover1 ?? "/placeholder.svg",
          photoCount: totalCount,
<<<<<<< HEAD
<<<<<<< HEAD
          videos: album?.videos,
=======
>>>>>>> b5905f9 (Fresh clean commit)
        });
=======
albums.push({
            slug,
            category: cat,
            displayName: albumDisplayName(slug, cat),
            cover: cover1 || "/placeholder.svg",
            coverAlt: cover2 ?? cover1 ?? "/placeholder.svg",
            photoCount: totalCount,
            videos: album?.videos,
          });
>>>>>>> 70848b6 (Update contact details, instagram, portfolio filters, add shweta-pranav pre-wedding photos, remove large video files from tracking)
=======
          videos: album?.videos,
        });
>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
      }
    }

    // Loose photos → treat as a "Highlights" album if any exist
    if (data.loose?.length > 0) {
      albums.push({
        slug: "_highlights",
        category: cat,
        displayName: `${CATEGORY_LABELS[cat]} Highlights`,
        cover: data.loose[0],
        coverAlt: data.loose[1] ?? data.loose[0],
        photoCount: data.loose.length,
      });
    }
  }

  return albums;
}

/* ─── Get exact details for an album including events ─── */

export function getAlbumDetails(manifest: Manifest, category: CategoryKey, albumSlug: string): Album | null {
  const data = manifest.categories[category];
  if (!data) return null;
  if (albumSlug === "_highlights") return { photos: data.loose ?? [] };
  return data.albums?.[albumSlug] ?? null;
}

/* ─── Get photos for a specific album (flat array) ─── */

export function getAlbumPhotos(
  manifest: Manifest,
  category: CategoryKey,
  albumSlug: string,
): string[] {
  const details = getAlbumDetails(manifest, category, albumSlug);
  if (!details) return [];
  const all = [...(details.photos || [])];
  if (details.events) {
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
    // For wedding category, prioritize "wedding" event photos
    if (category === "wedding") {
      const eventEntries = Object.entries(details.events);
      for (const [key, ev] of [...eventEntries.filter(([k]) => k.toLowerCase() === "wedding"),
          ...eventEntries.filter(([k]) => k.toLowerCase() !== "wedding")]) {
        all.push(...ev);
      }
    } else {
      for (const ev of Object.values(details.events)) all.push(...ev);
    }
<<<<<<< HEAD
=======
    for (const ev of Object.values(details.events)) all.push(...ev);
>>>>>>> b5905f9 (Fresh clean commit)
=======
>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
  }
  return all;
}

/* ─── Highlights per category (capped) — homepage reel ─── */

export function getHighlights(
  manifest: Manifest,
  cap = HIGHLIGHTS_PER_CATEGORY,
): GalleryItem[] {
  const items: GalleryItem[] = [];
  for (const cat of PUBLIC_CATEGORIES) {
    const data = manifest.categories[cat];
    if (!data) continue;
<<<<<<< HEAD
<<<<<<< HEAD
    const all = getAllPhotos(data, cat);
=======
    const all = getAllPhotos(data);
>>>>>>> b5905f9 (Fresh clean commit)
=======
    const all = getAllPhotos(data, cat);
>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
    for (const src of all.slice(0, cap)) {
      items.push({ src, category: cat, label: CATEGORY_LABELS[cat] });
    }
  }
  return items;
}

/* ─── Pick N images from a single category ─── */

export function pickFromCategory(
  manifest: Manifest,
  category: CategoryKey,
  count: number,
): string[] {
  const data = manifest.categories[category];
  if (!data) return [];
<<<<<<< HEAD
<<<<<<< HEAD
  return getAllPhotos(data, category).slice(0, count);
=======
  return getAllPhotos(data).slice(0, count);
>>>>>>> b5905f9 (Fresh clean commit)
=======
  return getAllPhotos(data, category).slice(0, count);
>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
}

/* ─── Get all photos across categories for Masonry Grid ─── */
export function getAllMixedPhotos(manifest: Manifest, filterCat?: CategoryKey): string[] {
  const out: string[] = [];
  const lists = PUBLIC_CATEGORIES.map((cat) => {
    if (filterCat && filterCat !== cat) return [];
    const data = manifest.categories[cat];
<<<<<<< HEAD
<<<<<<< HEAD
    return data ? getAllPhotos(data, cat) : [];
=======
    return data ? getAllPhotos(data) : [];
>>>>>>> b5905f9 (Fresh clean commit)
=======
    return data ? getAllPhotos(data, cat) : [];
>>>>>>> 0dfef5b (Fix wedding album photo priority, add category tags to albums, update Instagram name)
  });

  // Calculate the maximum length among all lists to know when to stop
  const maxLength = Math.max(...lists.map((l) => l.length));

  for (let i = 0; i < maxLength; i++) {
    for (const list of lists) {
      if (list[i]) {
        out.push(list[i]);
      }
    }
  }
  return out;
}
